[package]
name = "grcov"
version = "0.1.33"
authors = ["Marco Castelluccio <mcastelluccio@mozilla.com>"]
links = "llvmgcov"
build = "build.rs"

[build-dependencies]
cc = "^1.0"

[dependencies]
crossbeam = "^0.3"
serde_json = "^1.0"
walkdir = "^2.0"
num_cpus = "^1.7"
semver = "^0.9"
rust-crypto = "^0.2"
zip = { version = "^0.2", default-features = false }
tempdir = "^0.3"
uuid = { version = "^0.5", features = ["v4"] }
libc = "^0.2"
clap = {version = "2.31", features = ["yaml"]}

[features]
# For the system allocator feature.
alloc_system = []
